/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dia4;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
      Scanner leitor = new Scanner (System.in);
      
        System.out.println("Digite o seu nome: ");
        String nome = leitor.nextLine();
        
        System.out.println("Digite o seu salário fixo em reais: ");
        int salario = leitor.nextInt();
        
        System.out.println("Digite o total de suas vendas em reias: ");
        int vendas = leitor.nextInt();        
        
        int salarioTotal = salario + (15*vendas)/100;
        
        System.out.println("Nome: " + nome);
        System.out.println("Salário fixo: " + salario);
        System.out.println("Salário total: " + salarioTotal);
        
    }
}
